name: PreFlightWB
options:
  bundleIdPrefix: com.valderis
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    INFOPLIST_KEY_CFBundleDisplayName: "PreFlight W&B"
    INFOPLIST_KEY_UILaunchStoryboardName: "LaunchScreen"
    INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
    INFOPLIST_KEY_UIRequiresFullScreen: "YES"
    INFOPLIST_KEY_ITSAppUsesNonExemptEncryption: "NO"
    INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.utilities"

targets:
  PreFlightWB:
    type: application
    platform: iOS
    sources:
      - path: PreFlightWB
        excludes:
          - "**/.DS_Store"
    entitlements:
      path: PreFlightWB/PreFlightWB.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.valderis.preflightwb
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: 4F4Q566K62
        TARGETED_DEVICE_FAMILY: "1"
    dependencies:
      - package: GoogleSignIn
    info:
      path: PreFlightWB/Info.plist
      properties:
        CFBundleDisplayName: "PreFlight W&B"
        ITSAppUsesNonExemptEncryption: false
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false

  PreFlightWBTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PreFlightWBTests
    dependencies:
      - target: PreFlightWB
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.valderis.preflightwb.tests

packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "8.0.0"
